#!/bin/sh -eu

git rev-parse --show-toplevel   # go to the root of the repo

die() { echo "$@"; exit 1; }
gnu_sed() { sed --version &> /dev/null; }

project_name=$(basename $PWD | tr '-' '_')
files=$(git grep -l AAI | grep -v $(basename $0))
name=$(git config user.name)
year=$(date +%Y)

if gnu_sed >/dev/null 2>&1; then                         # Linux
    sed -i "s/AAI/$project_name/g" $files
    sed -i 's/<year>/'$year'/; s/<name>/'$name'/' LICENSE
else                                                     # BSD/MacOS
    sed -i "" "s/AAI/$project_name/g" $files
    sed -i "" "s/<year>/$year/; s/<name>/$name/" LICENSE
fi
git mv src/AAI src/$project_name

sed -i 's/<year>/'$year'/; s/<name>/'$name'/' 

echo 'Now write a good README.md!!!'
